### ISSUE TITLE
Questions about the results

### ISSUE THREAD

**Issue by mgao97** [nickruggeri/Hy-MMSBM#2]
Hi~

Thanks for your great work. I am confused about the results according to the code. What are the relationships among u, w and the detected community structures, I mean, the community index for each node.

I am looking forward to your response.

**Comment by nickruggeri** [comment]
Hi @mgao97, 

thanks for the question. 
In Hy-MMSBM there are K communities and N nodes.
Therefore, a community index `a` is an integer between 0 and K-1, and a node `i` an integer between 0 and N-1.

Given the above, the belonging of a node `i` to community `a` is a float stored inside `u[i, a]`.
Similarly, `w` is the affinity matrix, therefore the affinity between two communities `a` and `b` is stored in `w[a, b]` (possibly `a=b`).

Hope this helps!

**Comment by mgao97** [comment]
Thank you for your helpful message!

It is clear to me :)
